language: python
python:
  - "2.7"
cache: pip
before_install:
  - pip install -U pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r test/test-requirements.txt
script:
  - python test/test_awxInventory.py